function [BW_out,properties] = filterRegionsXX(BW_in)
%filterRegions Filter BW image using auto-generated code from imageRegionAnalyzer app.

% Auto-generated by imageRegionAnalyzer app on 15-Oct-2023
%---------------------------------------------------------

BW_out = BW_in;

% Filter image based on image properties.
BW_out = bwpropfilt(BW_out,'Area',[2000, 99000]);%3000 25599 28000 70000
BW_out = bwpropfilt(BW_out,'MajorAxisLength',[400, 1700]);%795 1300
BW_out = bwpropfilt(BW_out,'MinorAxisLength',[100, 350]);%213 240

% Get properties.
properties = regionprops(BW_out, {'Area', 'ConvexArea', 'Eccentricity', 'EquivDiameter', 'EulerNumber', 'Extent', 'FilledArea', 'MajorAxisLength', 'MinorAxisLength', 'Orientation', 'Perimeter', 'Solidity'});