function [BW_out,properties] = filterRegionsC(BW_in)
%filterRegions Filter BW image using auto-generated code from imageRegionAnalyzer app.

% Auto-generated by imageRegionAnalyzer app on 14-Oct-2023
%---------------------------------------------------------

BW_out = BW_in;

% Filter image based on image properties.
BW_out = bwpropfilt(BW_out,'Area',[3000, 37000]);%20000
BW_out = bwpropfilt(BW_out,'Solidity',[0, 0.65]);

% Get properties.
properties = regionprops(BW_out, {'Area', 'Eccentricity', 'EquivDiameter', 'Extent', 'FilledArea', 'MajorAxisLength', 'MinorAxisLength', 'Perimeter', 'Solidity'});